config:
  install_tree:
    projections:
      all: ${PACKAGE}/${VERSION}/${HASH:7}
    root: /work/modules/automatic/spack/envs/aalto-ubuntu2004-skylake-dev/software
  module_roots:
    tcl: /work/modules/automatic/spack/envs/aalto-ubuntu2004-skylake-dev/modules
    lmod: /work/modules/automatic/spack/envs/aalto-ubuntu2004-skylake-dev/lmod
  source_cache: /cache/spack
  misc_cache: /tmp/spack_misc_cache
  build_stage:
    - $spack/var/spack/stage
  locks: false
  build_language: 'en_US.utf8'
