- method: rsync
  source: /work/modules/automatic/spack/envs/aalto-ubuntu2004-skylake-dev/software
  dest: /tw-scicomp/software
  rsync_flags: -surlptDxv  --exclude='.nfs*' --exclude='.snapshot*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  use_ssh: False
  delete: false
- method: rsync
  source: /work/modules/automatic/spack/envs/aalto-ubuntu2004-skylake-dev/lmod
  dest: /tw-scicomp/lmod
  rsync_flags: -surlptDxv  --exclude='.nfs*' --exclude='.snapshot*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  use_ssh: False
  delete: false
