packages:
  boost:
    variants: +pic
  cairo:
    variants: +X +gobject +pdf +fc
  charmpp:
    variants: backend=mpi
  curl:
    variants: +libssh2 ~nghttp
  cuda:
    version: [11.5.0]
  fftw:
    variants: +openmp
  flex:
    version: [2.6.4]
  fontconfig:
    version: [2.13.1]
  gcc:
    version: [8.4.0, 9.3.0, 6.5.0]
    variants: +piclibs
  go:
    version: [1.18.3]
  graphviz:
    variants: +expat ~ghostscript ~gtkplus +gts ~java +libgd ~pangocairo ~qt
  harfbuzz:
    variants: +graphite2
  hdf5:
    variants: +cxx +fortran +hl +pic +shared +szip +threadsafe
  latte:
    variants: +progress
  llvm:
    version: [13.0.0]
    variants: +python
  mesa:
    variants: +glx +llvm +opengl +osmesa swr=avx2
  meson:
    version: [0.59.2]
  netcdf-c:
    version: [4.7.4]
  openblas:
    version: [0.3.13]
    variants: +virtual_machine threads=openmp +pic
  openjdk:
    version: [11.0.8_10]
  openmpi:
    version: [4.0.5]
    variants: fabrics=none +thread_multiple schedulers=none
  openssl:
    externals:
      - spec: openssl@1.1.1f
        prefix: /usr
    buildable: False
  pango:
    version: [1.41.0]
    variants: +X
  pcre:
    variants: +jit +utf
  pkgconf:
    version: [1.7.3]
  python:
    version: [3.8.7]
    variants: +pic +shared +optimizations +uuid +pythoncmd
  qmd-progress:
    variants: +graphlib
  qt:
    variants: +phonon +dbus +opengl +webkit
  r:
    version: [4.1.1]
    variants: +X +external-lapack
  sqlite:
    version: [3.34.0]
    variants: +column_metadata +fts +functions +rtree
  vim:
    variants: features=huge
  all:
    compiler: [gcc@8.4.0, gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [openjdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
