installer_checksums:
  Miniconda3-latest-Linux-x86_64.sh: 'bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2'
  Miniconda3-4.7.12.1-Linux-x86_64.sh: 'bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2'
  Miniconda3-py37_4.8.2-Linux-x86_64.sh: '957d2f0f0701c3d1335e3b39f235d197837ad69a944fa6f5d8ad2c686b69df3b'
  Anaconda3-2019.10-Linux-x86_64.sh: '46d762284d252e51cd58a8ca6c8adc9da2eadc82c342927b2f66ed011d1d8b53'
  Anaconda3-2020.02-Linux-x86_64.sh: '2b9f088b2022edb474915d9f69a803d6449d5fdb4c303041f60ac4aefcc208bb'
environments:
  - name: miniconda
    version: '4.7.12.1'
    miniconda: True
    python_version: 3
    installer_version: '4.7.12.1'
    condarc:
      channels:
        - defaults
  - name: anaconda
    version: '2020-02-tf1'
    miniconda: False
    python_version: 3
    installer_version: '2019.10'
    freeze: True
    condarc:
      channels:
        - defaults
        - pytorch
        - gurobi
        - IBMDecisionOptimization
        - anaconda
        - mosek
        - conda-forge
    collections:
      - tensorflow-v1
      - triton-generic
  - name: anaconda
    version: '2020-02-tf2'
    miniconda: False
    python_version: 3
    installer_version: '2019.10'
    freeze: True
    condarc:
      channels:
        - defaults
        - pytorch
        - gurobi
        - IBMDecisionOptimization
        - anaconda
        - mosek
        - conda-forge
    collections:
      - tensorflow-v2
      - triton-generic
  - name: anaconda
    version: '2020-03-tf1'
    miniconda: True
    python_version: 3
    installer_version: 'py37_4.8.2'
    condarc:
      channels:
        - pytorch
        - defaults
        - gurobi
        - IBMDecisionOptimization
        - mosek
        - rapidsai
        - conda-forge
    collections:
      - tensorflow-v1
      - triton-generic
  - name: anaconda
    version: '2020-03-tf2'
    miniconda: False
    python_version: 3
    installer_version: 'py37_4.8.2'
    condarc:
      channels:
        - pytorch
        - defaults
        - gurobi
        - IBMDecisionOptimization
        - mosek
        - rapidsai
        - conda-forge
    collections:
      - tensorflow-v2
      - triton-generic
#  - name: neuroimaging
#    version: '2020-01'
#    miniconda: False
#    python_version: 3
#    installer_version: '2020.02'
#    condarc:
#      channels:
#        - defaults
#        - pytorch
#        - r
#        - conda-forge
#    collections:
#      - neuroimaging
collections:
  tensorflow-v1:
collections:
  tensorflow-v1:
    conda_packages:
      - tensorboard
      - tensorboard-plugin-wit
      - tensorflow=1.15.0
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  tensorflow-v2:
    conda_packages:
      - tensorboard
      - tensorboard-plugin-wit
      - tensorflow=2.*.*
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  triton-generic:
    pip_packages:
      - bash-kernel
      - jupyterlab-git
      - matlab-kernel
      - nbscript
      - nbval
      - nbzip
      - opencv-contrib-python
      - pymanopt
      - python-igraph
      - roboschool
    conda_packages:
      - appdirs
      - asn1crypto
      - astor
      - astropy
      - atomicwrites
      - astunparse
      - backports
      - bcolz
      - bcrypt
      - beautifulsoup4
      - bitarray
      - bkcharts
      - blaze
      - blinker
      - bokeh
      - boto
      - bottleneck
      - cachetools
      - cairo
      - cffi
      - chardet
      - cloudpickle
      - clyent
      - colorama
      - conda
      - conda-env
      - conda-tree
      - configargparse
      - contextlib2
      - coverage
      - cplex
      - cryptography
      - cryptography-vectors
      - cuda100
      - cudatoolkit
      - cudnn
      - cupy
      - cusignal
      - cython
      - dill
      - distributed
      - docopt
      - docutils
      - fastcache
      - fastparquet
      - feather-formata
      - filelock
      - fribidi
      - glob2
      - gmpy2
      - google-auth-oauthlib
      - gpy
      - graphite2
      - greenlet
      - gurobi
      - h5py
      - harfbuzz
      - hdf4
      - hdf5
      - heapdict
      - html5lib
      - importnb
      - ipdb
      - ipykernel
      - ipyparallel
      - ipython
      - ipywidgets
      - jbig
      - jdcal
      - joblib
      - jupyter
      - jupyter_contrib_nbextensions
      - jupyterlab
      - jupyterlab_server
      - jupytext
      - keras
      - keyring
      - llvmlite
      - lxml
      - markdown
      - matplotlib
      - metakernel
      - mkl
      - mkl-service
      - mkl_fft
      - mkl_random
      - mne
      - mock
      - more-itertools
      - mosek
      - mpi4py
      - mpich
      - nbconvert
      - nbdime
      - nbstripout
      - nbval
      - nccl
      - networkx
      - nitime
      - nltk
      - nose
      - numba
      - numexpr
      - numpy
      - numpydoc
      - oauthlib
      - olefile
      - openmp
      - openpyxl
      - pandas
      - pandoc
      - pango
      - parquet-cpp
      - partd
      - patchelf
      - path
      - path.py
      - pathlib2
      - pbr
      - pep8
      - phonopy
      - pillow
      - pip
      - pipdeptree
      - pixman
      - pkginfo
      - plotly
      - ply
      - prometheus_client
      - protobuf
      - py-lief
      - pyarrow
      - pybind11
      - pycodestyle
      - pycrypto
      - pycurl
      - pydicom
      - pyflakes
      - pygments
      - pygpu
      - pyjwt
      - pylint
      - pympler
      - pyopenssl
      - pyparsing
      - pysocks
      - pytables
      - pytest
      - pytest-arraydiff
      - pytest-astropy
      - pytest-doctestplus
      - pytest-openfiles
      - pytest-remotedata
      - python
      - python-dateutil
      - python-libarchive-c
      - python-snappy
      - pytorch
      - pytz
      - pyyaml
      - requests
      - requests-oauthlib
      - ripgrep
      - rsa
      - scikit-image
      - scikit-learn
      - seaborn
      - setuptools
      - simplegeneric
      - singledispatch
      - six
      - sortedcollections
      - sphinx
      - sphinxcontrib
      - sphinxcontrib-websupport
      - sphinx_rtd_theme
      - spyder
      - sqlalchemy
      - sqlite
      - statsmodels
      - sympy
      - theano
      - thrift
      - torchvision
      - twisted
      - typing
      - unicodecsv
      - unixodbc
      - vtk
      - wheel
      - xgboost
      - xlrd
      - xlsxwriter
      - xlwt
      - xmltodict
  neuroimaging:
    conda_packages:
      - python=3.7
      - captum
      - cffi
      - configobj
      - cupy
      - cudatoolkit
      - cython
      - flake8
      - gensim
      - gevent
      - greenlet
      - h5py
      - ipywidgets
      - joblib
      - jupyter
      - lxml
      - matplotlib
      - memory_profiler
      - mkl
      - mpmath
      - msgpack-python
      - networkx
      - nose
      - numba
      - numpy
      - numpydoc
      - openpyxl
      - opencv
      - pandas
      - pillow
      - pip
      - plotly
      - psutil
      - pycairo
      - pyopengl
      - pyqt
      - pyserial
      - pytables
      - pytest
      - pytest-cov
      - pytorch
      - pyyaml
      - pyzmq
      - requests[security]
      - r-essentials
      - r-lme4
      - r-lmertest
      - rpy2
      - r-tidyverse
      - scikit-learn
      - scipy
      - seaborn
      - shapely
      - sphinx
      - spyder
      - statsmodels
      - sympy
      - tensorflow
      - tensorflow-gpu
      - torchvision
      - tornado
      - tqdm
      - vispy
      - vtk=8.1.2
      - wxpython
      - xlrd
    pip_packages:
      - autoreject
      - bert-serving-server
      - bert-serving-client
      - bids_validator
      - codespell
      - dipy
      - doit
      - doit-graph
      - ipyevents
      - json-tricks
      - jupyter_contrib_nbextensions
      - librosa
      - mayavi
      - mne
      - mne-bids
      - moviepy
      - neo
      - nibabel
      - nilearn
      - nipy
      - nipype
      - nitime
      - psychopy
      - psychopy_ext
      - pycortex
      - pydocstyle
      - pyface
      - pygame
      - pyglet
      - pyosf
      - pyparallel
      - pysoundcard
      - pysoundfile
      - pysurfer
      - pytest-faulthandler
      - pytest-sugar
      - python-bidi
      - python-picard
      - pythreejs
      - pyvista
      - rise
      - sounddevice
      - spacy
      - sphinx_bootstrap_theme
      - sphinx_fontawesome
      - sphinx-gallery
      - traits
      - traitsui
      - transformers
      - zmq
      - "https://github.com/AaltoImagingLanguage/conpy/archive/master.zip"
      - "https://github.com/wmvanvliet/posthoc/archive/master.zip"
      - "https://github.com/wmvanvliet/mne_microstates/archive/master.zip"
      - "https://github.com/wmvanvliet/mne-rsa/archive/master.zip"

