installer_checksums:
  Miniconda3-py37_4.9.2-Linux-x86_64.sh: '79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31'
  Miniconda3-py38_4.9.2-Linux-x86_64.sh: '1314b90489f154602fd794accfc90446111514a5a72fe1f71ab83e07de9504a7'
environments:
  - name: miniconda
    version: '4.9.2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    condarc:
      channels:
        - defaults
  - name: anaconda
    version: '2021-01-tf2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    condarc:
      channels:
        - pytorch
        - rapidsai
        - defaults
        - conda-forge
        - nvidia
        - gurobi
        - IBMDecisionOptimization
        - mosek
    collections:
      - tensorflow-v2
      - triton-generic
  - name: neuroimaging
    version: '2021-01'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    condarc:
      channels:
        - defaults
        - conda-forge
    collections:
      - neuroimaging
collections:
  tensorflow-v1:
    conda_packages:
      - tensorboard
      - tensorboard-plugin-wit
      - tensorflow=1.15.0
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  tensorflow-v2:
    conda_packages:
      - tensorboard
      - tensorboard-plugin-wit
      - tensorflow=2.2.*
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  triton-generic:
    pip_packages:
      - bash-kernel
      - jupyterlab-git
      - matlab-kernel
      - nbscript
      - nbval
      - nbzip
      - opencv-contrib-python
      - pymanopt
      - python-igraph
      - roboschool
      - snakemake
    conda_packages:
     - astropy
     - bcolz
     - beautifulsoup4
     - bitarray
     - bkcharts
     # - blaze # No python3.8 build
     - boto
     - bottleneck
     - clyent
     - conda-tree
     - configargparse
     - contextlib2
     - cplex
     - cudatoolkit=10.1.*
     - cudf
     - cuml
     - cugraph
     - cusignal
     - cuspatial
     - cuxfilter
     - cython
     - dill
     - docopt
     - filelock
     - glob2
     - gpy
     - greenlet
     - gurobi
     - html5lib
     - importnb
     - iniconfig
     - ipdb
     - jbig
     - jupyter
     - jupyter_contrib_nbextensions
     - jupyterlab
     - jupytext
     - keras
     - metakernel
     - mne
     - more-itertools
     - mosek
     - mpi4py
     - nbdime
     - nbstripout
     - nbval
     - nitime
     - nltk
     - nose
     - openmp
     - openpyxl
     - pango
     - patchelf
     - path.py
     - pathlib2
     - pbr
     - pep8
     - phonopy
     - pipdeptree
     - pkginfo
     - plotly
     - ply
     - py
     - py-lief
     - pyarrow
     - pybind11
     - pycrypto
     - pycurl
     - pympler
     - pytest-astropy
     - python-libarchive-c
     - python-snappy
     - python=3.8.*
     - pytorch=1.7.*
     - ripgrep
     - scikit-image
     - seaborn
     - sh
     - simplegeneric
     - singledispatch
     - sortedcollections
     - sphinx_rtd_theme
     - sphinxcontrib-websupport
     - spyder
     - sympy
     - theano
     - twisted
     - typing
     - unicodecsv
     - unixodbc
     - xgboost
     - xlsxwriter
     - xlwt
     - xmltodict
  neuroimaging:
    conda_packages:
      - python>=3.8
      - pip
      - numpy
      - scipy
      - matplotlib
      - numba
      - pandas
      - xlrd
      - scikit-learn
      - h5py
      - pillow
      - statsmodels
      - jupyter
      - joblib
      - psutil
      - numexpr
      - traits
      - pyface
      - traitsui
      - imageio
      - tqdm
      - spyder-kernels>=1.10.0
      - imageio-ffmpeg>=0.4.1
      - vtk>=9.0.1
      - pyvista>=0.24
      - pyvistaqt>=0.2.0
      - mayavi
      - PySurfer
      - dipy
      - nibabel
      - nilearn
      - python-picard
      - pyqt
      - mne
      - mffpy>=0.5.7
    pip_packages:
      - autoreject
      - bids_validator
      - codespell
      - nipy
      - nipype
      - nitime
      - sphinx_bootstrap_theme
      - sphinx_fontawesome
      - sphinx-gallery
      - "https://github.com/AaltoImagingLanguage/conpy/archive/master.zip"
      - "https://github.com/wmvanvliet/posthoc/archive/master.zip"
      - "https://github.com/wmvanvliet/mne_microstates/archive/master.zip"
      - "https://github.com/wmvanvliet/mne-rsa/archive/master.zip"
