installer_checksums:
  Miniconda3-py37_4.9.2-Linux-x86_64.sh: '79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31'
  Miniconda3-py38_4.9.2-Linux-x86_64.sh: '1314b90489f154602fd794accfc90446111514a5a72fe1f71ab83e07de9504a7'
  Miniconda3-py38_4.10.3-Linux-x86_64.sh: '935d72deb16e42739d69644977290395561b7a6db059b316958d97939e9bdf3d'
  Miniconda3-py39_4.10.3-Linux-x86_64.sh: '1ea2f885b4dbc3098662845560bc64271eb17085387a70c2ba3f29fff6f8d52f'
  Mambaforge-4.11.0-0-Linux-x86_64.sh: '49268ee30d4418be4de852dda3aa4387f8c95b55a76f43fb1af68dcbf8b205c3'
  Mambaforge-22.11.1-4-Linux-x86_64.sh: '16c7d256de783ceeb39970e675efa4a8eb830dcbb83187f1197abfea0bf07d30'
  Mambaforge-23.1.0-1-Linux-x86_64.sh: 'cfb16c47dc2d115c8b114280aa605e322173f029fdb847a45348bf4bd23c62ab'
  Miniforge3-4.12.0-2-Linux-x86_64.sh: 'e8bd60572d1bdcd9fc16114f423653c95e02f0be1393383f77fba17cf8acb10e'
  Miniforge3-22.11.1-4-Linux-x86_64.sh: '737d1b2666528416706a916b355c43ff58deeaebf5ca906bc1a551e96c73ab8e'
environments:
  - name: miniconda
    version: '4.12.0-2'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    condarc_install:
      channels:
        - conda-forge
  - name: anaconda
    version: '2023-04'
    miniconda: False
    miniforge: False
    mambaforge: True
    mamba: True
    python_version: 3
    installer_version: '23.1.0-1'
    conda_override_cuda: '11.8'
    condarc_install:
      channels:
        - pytorch
        - nvidia
        - huggingface
        - conda-forge
        - gurobi
        - mosek
      channel_priority: flexible
    collections:
      - compilers
      - cuda-compiler
      - deep_learning_extras
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - gurobi
      - mne
      - cplex_pip
      - mosek
      - opencv-pip
      - pyg-pip
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
        GRB_LICENSE_FILE: '/share/apps/manual_installations/gurobi/license/gurobi.lic'
  - name: neuroimaging
    version: '2023-03'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    conda_override_cuda: '11.8'
    condarc_install:
      channels:
        - pytorch
        - nvidia
        - huggingface
        - conda-forge
      channel_priority: flexible
    collections:
      - triton-generic
      - deep_learning_extras
      - pytorch
      - neuroimaging
      - pyg-pip
collections:
  compilers:
    conda_packages:
      - compilers
      - gcc>=11,<12
      - gxx>=11,<12
      - gfortran>=11,<12
  cplex:
    conda_packages:
      - cplex
  cplex_pip:
    pip_packages:
      - cplex
  gurobi:
    conda_packages:
      - gurobi=9.5.2
  gurobi_pip:
    pip_packages:
      - gurobipy
  mosek:
    conda_packages:
      - mosek
  tensorflow-pip:
    pip_packages:
      - tensorflow==2.12.*
    conda_packages:
      - numpy=1.23.4
      - tensorboard<2.13,>=2.12
      - grpcio=1.51.1
      - wrapt<1.15
  tensorflow-v2-conda-forge:
    conda_packages:
      - cudatoolkit=11.*
      - cudnn>=8.2
      - tensorflow=2.12*=cuda11*
  cuda-compiler:
    # NVCC from nvidia channel
    conda_packages:
      - cuda-compiler=11.8
      - cuda-libraries-dev=11.8
  rapidsai:
    conda_packages:
      - rapids=23.*
  pytorch:
    conda_packages:
      - cudnn>=8.3
      - pytorch::pytorch=2.1.*
      - pytorch::pytorch-cuda=11.8
      - pytorch::torchaudio
      - pytorch::torchvision
      - pytorch::pytorch-mutex=*=cuda
  pyg-pip:
    pip_packages:
      # conda installed pyg currently only supports pytorch 2.0
      - "torch_geometric -f https://data.pyg.org/whl/torch-2.1.0+cu118.html"
      # pyg_lib missing from pytorch 2.1 pip file index
      # - pyg_lib 
      - torch_scatter
      - torch_sparse
      - torch_cluster
      - torch_spline_conv
  deep_learning_extras:
    conda_packages:
      - cudatoolkit=11.8
      - cudnn>=8.6
      - datasets
      #- dm-haiku
      #- flax
      - gymnasium # =0.26.3 # Version lock due to ray
      - lightning
      #- jax>=0.4
      #- jaxlib>=0.4=cuda*
      - ogb
      - pytorch-lightning
      - py-xgboost
      - transformers
      - tensorboard
      - tensorboardx
      - wandb
    pip_packages:
      - "jax[cuda11_pip] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
      - flax
      - dm-haiku
      - deepspeed
      - dm-sonnet
      - reverb
      # Ray's conda package depends on nvidia-ml-py, which conflicts with scalene
      - ray[default]
      - ray[air]
      - ray[data]
      - ray[tune]
      - ray[rllib]
  opencv-pip:
    pip_packages:
      - opencv-contrib-python
  mne:
    conda_packages:
      - mne
  triton-generic:
    pip_packages:
      - bash_kernel
      - forthon
      - matlab-kernel
      - mppl
      - nbscript
      - nbzip
      - pymanopt
      - snakemake
      - python-hostlist
    conda_packages:
      - astropy
      - attrs
      # - bcolz # No longer maintained
      - beautifulsoup4
      - bitarray
      # - blaze # No python3.8 build
      - black
      - bokeh
      - boto
      - bottleneck
      - cartopy
      #- clyent # Deprecated package
      - conda-tree
      - configargparse
      - contextlib2
      - crc32c
      - cryptography
      - cython
      - dask
      - datalad
      - datashader
      - dill
      - docopt
      - easygui
      - fastapi
      - filelock
      - flake8
      - glob2
      - gpy
      - graph-tool
      - greenlet
      - h5py=*=mpi_openmpi*
      - h5netcdf
      - hdf5=*=mpi_openmpi*
      - html5lib
      - hydra-core
      - igraph
      - importnb
      - iniconfig
      - ipdb
      - ipympl    # jupyter + matplotlib interactive
      - jbig
      - joblib
      - jsonlines
      - jupyter
      - jupyter_contrib_nbextensions
      - jupyterlab
      - jupyterlab-git
      - jupytext
      - libblas=*=*mkl*
      # pytorch libjpeg-turbo is too old for tensorflow
      - conda-forge::libjpeg-turbo
      - librosa
      - libwebp>=1.3.2 # CVE-2023-4863
      - libxscrnsaver-cos6-x86_64
      - line_profiler
      - metakernel
      - more-itertools
      - mpi4py
      - nbdime
      - nbstripout
      - nbval
      - nitime
      - nltk
      - nose
      - notebook<7
      - networkx
      - numba
      - numexpr
      - numpy
      - openpyxl
      #- opencv # Disabling opencv due to different harfbuzz as tensorflow
      - pandera
      - pango
      - patchelf
      - path.py
      - pathlib2
      - pbr
      - pep8
      - phonopy
      - pipdeptree
      - pkginfo
      - plotly
      - ply
      - poetry
      - prometheus_client
      - py
      - py-lief
      - pyarrow=*=*cuda
      - pybind11
      - pybullet
      - pycurl
      - pydantic
      - pympler
      - pyqtwebengine
      - pysoundfile
      - pytest
      - pytest-astropy
      - python-igraph
      - python-libarchive-c
      - python-snappy
      - requests>=2.28
      - ripgrep
      - scalene
      - scikit-image
      - seaborn
      - sh
      - shapely
      - simplegeneric
      - singledispatch
      - sortedcollections
      - sphinx_rtd_theme
      - sphinxcontrib-websupport
      - spyder>=5.4.2 # Fixes OOD bug
      - spyder-line-profiler
      - streamlit
      - sympy
      - twisted
      - typing
      - typer
      - ucx
      - unicodecsv
      - unixodbc
      - webdataset
      - xarray
      - xgboost
      - xlsxwriter
      - xlwt
      - xmltodict
      - zstandard
  triton-r-generic:
    conda_packages:
      - r-essentials
      - rstudio
      - "'blas * mkl'"
  neuroimaging:
    conda_packages:
      - autoreject
      - bids-validator
      - cupy
      - fooof
      - gensim
      - h5io
      - h5py
      - mne
      - mne-bids
      - mne-connectivity
      - mne-faster
      - mne-microstates
      - mne-nirs
      - mne-qt-browser
      - mne-rsa
      - neurokit2
      - nibabel
      - nilearn
      - nipype
      - nitime
      - numba
      - psychopy
      - pydata-sphinx-theme
      - pydocstyle
      - pymatreader
      - pyosf
      - pytest-faulthandler
      - pytest-sugar
      - python-bidi
      - python-picard
      - python-picard
      - pyvista>=0.30
      - pyvistaqt>=0.4
      - qdarkstyle
      - scikit-learn
      - sphinx-gallery
      - statsmodels
    pip_packages:
      - "https://github.com/wmvanvliet/posthoc/archive/master.zip"
      - "https://github.com/AaltoImagingLanguage/conpy/archive/master.zip"
      - filename-templates
      - psychtoolbox
      - pygame
      - pyo
      - pyparallel
      - rapidtide
      - sphinx-bootstrap-theme
      - sphinxcontrib-bibtex
      - sphinxcontrib-youtube
      - sphinx-copybutton
      - sphinx-design
      - sphinx-fontawesome
      - websocket_client
