installer_checksums:
  Miniconda3-py37_4.9.2-Linux-x86_64.sh: '79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31'
  Miniconda3-py38_4.9.2-Linux-x86_64.sh: '1314b90489f154602fd794accfc90446111514a5a72fe1f71ab83e07de9504a7'
  Miniconda3-py38_4.10.3-Linux-x86_64.sh: '935d72deb16e42739d69644977290395561b7a6db059b316958d97939e9bdf3d'
  Miniconda3-py39_4.10.3-Linux-x86_64.sh: '1ea2f885b4dbc3098662845560bc64271eb17085387a70c2ba3f29fff6f8d52f'
  Mambaforge-4.11.0-0-Linux-x86_64.sh: '49268ee30d4418be4de852dda3aa4387f8c95b55a76f43fb1af68dcbf8b205c3'
  Miniforge3-4.12.0-2-Linux-x86_64.sh: 'e8bd60572d1bdcd9fc16114f423653c95e02f0be1393383f77fba17cf8acb10e'
  Miniforge3-22.11.1-4-Linux-x86_64.sh: '737d1b2666528416706a916b355c43ff58deeaebf5ca906bc1a551e96c73ab8e'
environments:
  - name: miniconda
    version: '4.9.2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    freeze: True
    condarc:
      channels:
        - defaults
  - name: miniconda
    version: '4.12.0-2'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    condarc_install:
      channels:
        - conda-forge
  - name: anaconda
    version: '2021-01-tf2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    freeze: True
    condarc:
      channels:
        - pytorch
        - rapidsai
        - defaults
        - conda-forge
        - nvidia
        - gurobi
        - IBMDecisionOptimization
        - mosek
    collections:
      - tensorflow-v2
      - triton-generic
  - name: anaconda
    version: '2021-02-tf2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    freeze: True
    condarc:
      channels:
        - pytorch
        - rapidsai
        - defaults
        - conda-forge
        - nvidia
        - gurobi
        - IBMDecisionOptimization
        - mosek
    collections:
      - tensorflow-v2
      - triton-generic
  - name: anaconda
    version: '2021-03-tf2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    freeze: True
    condarc:
      channels:
        - pytorch
        - rapidsai
        - defaults
        - conda-forge
        - nvidia
        - gurobi
        - IBMDecisionOptimization
        - mosek
    collections:
      - tensorflow-v2
      - triton-generic
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: anaconda
    version: '2021-04-tf2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.10.3'
    freeze: True
    condarc_install:
      channels:
        - pytorch
        - conda-forge
        - gurobi
        - IBMDecisionOptimization
        - mosek
      channel_priority: flexible
    collections:
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - mne
      - gurobi
      - cplex
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: anaconda
    version: '2022-01'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    freeze: True
    condarc_install:
      channels:
        - pytorch
        - huggingface
        - conda-forge
        - mosek
      channel_priority: flexible
    collections:
      - deep_learning_extras
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - gurobi_pip
      - mne
      - cplex_pip
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: anaconda
    version: '2022-02'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    freeze: True
    condarc_install:
      channels:
        - pytorch
        - huggingface
        - conda-forge
        - mosek
      channel_priority: flexible
    collections:
      - deep_learning_extras
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - gurobi_pip
      - mne
      - cplex_pip
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: anaconda
    version: '2022-03'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    conda_override_cuda: '11.3'
    freeze: True
    condarc_install:
      channels:
        - pytorch
        - huggingface
        - conda-forge
        - mosek
      channel_priority: flexible
    collections:
      - deep_learning_extras
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - gurobi_pip
      - mne
      - cplex_pip
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: anaconda
    version: '2022-04'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    conda_override_cuda: '11.7'
    freeze: True
    condarc_install:
      channels:
        - pytorch
        - nvidia
        - huggingface
        - conda-forge
        - pyg
        - gurobi
        - mosek
      channel_priority: flexible
    collections:
      - deep_learning_extras
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - gurobi
      - mne
      - cplex_pip
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
        GRB_LICENSE_FILE: '/share/apps/manual_installations/gurobi/license/gurobi.lic'
  - name: anaconda
    version: '2023-01'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '22.11.1-4'
    conda_override_cuda: '11.7'
    condarc_install:
      channels:
        - pytorch
        - rapidsai
        - nvidia
        - huggingface
        - conda-forge
        - pyg
        - gurobi
        - mosek
      channel_priority: flexible
    collections:
      - deep_learning_extras
      - tensorflow-v2-conda-forge
      - pytorch
      - rapidsai
      - triton-generic
      - gurobi
      - mne
      - cplex_pip
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
        GRB_LICENSE_FILE: '/share/apps/manual_installations/gurobi/license/gurobi.lic'
  - name: rapidsai
    version: '21.10'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.10.3'
    freeze: True
    condarc_install:
      channels:
        - rapidsai
        - nvidia
        - conda-forge
        - gurobi
        - IBMDecisionOptimization
        - mosek
      channel_priority: flexible
    collections:
      - rapidsai
      - triton-generic
      - gurobi
      - cplex
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: anaconda-r
    version: '2021-01'
    miniconda: True
    python_version: 3
    installer_version: 'py39_4.10.3'
    condarc_install:
      channels:
        - r
        - defaults
        - conda-forge
      channel_priority: flexible
    collections:
      - triton-r-generic
  - name: neuroimaging
    version: '2021-01'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    freeze: True
    condarc:
      channels:
        - defaults
        - conda-forge
    collections:
      - neuroimaging
  - name: neuroimaging
    version: '2021-02'
    miniconda: True
    python_version: 3
    installer_version: 'py39_4.10.3'
    freeze: True
    condarc:
      channels:
        - defaults
        - conda-forge
    collections:
      - neuroimaging
  - name: neuroimaging
    version: '2022-01'
    miniconda: True
    python_version: 3
    installer_version: 'py39_4.10.3'
    freeze: True
    condarc_install:
      channels:
        - defaults
        - conda-forge
        - pytorch
        - nvidia
    collections:
      - neuroimaging
  - name: neuroimaging
    version: '2022-02'
    miniconda: True
    python_version: 3
    installer_version: 'py39_4.10.3'
    condarc_install:
      channels:
        - defaults
        - conda-forge
        - pytorch
        - nvidia
    collections:
      - neuroimaging
collections:
  cplex:
    conda_packages:
      - cplex
  cplex_pip:
    pip_packages:
      - cplex
  gurobi:
    conda_packages:
      - gurobi=9.5.2
  gurobi_pip:
    pip_packages:
      - gurobipy
  mosek:
    conda_packages:
      - mosek
  tensorflow-v1:
    conda_packages:
      - tensorboard
      - tensorboard-plugin-wit
      - tensorflow=1.15.0
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  tensorflow-v2:
    conda_packages:
      - cudatoolkit
      - tensorboard
      - tensorboard-plugin-wit
      - tensorflow=2.4.1=gpu_*
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  tensorflow-v2-pip:
    # Check this page for compatible versions of tensorflow, cudatoolkit and cudnn.
    # https://www.tensorflow.org/install/source#gpu
    conda_packages:
      - absl-py
      - astunparse
      - cudatoolkit=11.2.*
      - cudatoolkit-dev=11.2.*
      - cudnn=8.1.*
      - gast
      - google-pasta
      - grpcio
      - h5py
      - keras-preprocessing
      - libgcc-ng
      - libstdcxx-ng
      - numpy
      - opt_einsum
      - protobuf
      - python-flatbuffers
      - scipy
      - six
      - sqlite
      - termcolor
      - wrapt
      - zlib
    pip_packages:
      - tensorflow==2.6.0
  tensorflow-v2-conda-forge:
    conda_packages:
      - cudatoolkit=11.*
      - cudnn>=8.2
      - tensorboard
      - tensorflow=2.11.0*=cuda11*
  rapidsai:
    conda_packages:
      - rapids=23.02
  pytorch:
    conda_packages:
      - cudnn>=8.3
      - pytorch::pytorch-cuda=11.7
      - pytorch::torchaudio
      - pytorch::torchvision
      # torchvision dependencies
      #- ffmpeg
      #- jpeg
      #- libpng
      #- pillow
      #pip_packages:
      #- torchvision==0.11.3 # Specific version due to pytorch version: https://github.com/pytorch/vision
  pytorch-conda-forge:
    conda_packages:
      - cudatoolkit=11.*
      - pytorch=1.9.1=cuda11*
      - torchvision
  deep_learning_extras:
    conda_packages:
      - cudatoolkit>=11.3
      - cudnn>=8.3
      - datasets
      - dm-haiku
      - dm-sonnet
      - flax
      - gymnasium
      - jax
      - ogb
      - pyg
      - pytorch-lightning
      - py-xgboost-gpu
      - ray-all
      - transformers
      - wandb
    pip_packages:
      - deepspeed
      - reverb
  mne:
    conda_packages:
      - mne
  triton-generic:
    pip_packages:
      - bash-kernel
      - forthon
      - matlab-kernel
      - mppl
      - nbscript
      - nbzip
      - pymanopt
      - snakemake
      - webdataset
    conda_packages:
      - astropy
      - attrs
      # - bcolz # No longer maintained
      - beautifulsoup4
      - bitarray
      # - blaze # No python3.8 build
      - black
      - boto
      - bottleneck
      - cartopy
      - clyent
      - conda-tree
      - configargparse
      - contextlib2
      - cython
      - dask
      - datalad
      - dill
      - docopt
      - easygui
      - fastapi
      - filelock
      - flake8
      - glob2
      - gpy
      - graph-tool
      - greenlet
      - h5py
      - h5netcdf
      - html5lib
      - hydra-core
      - igraph
      - importnb
      - iniconfig
      - ipdb
      - ipympl    # jupyter + matplotlib interactive
      - jbig
      - joblib
      - jsonlines
      - jupyter
      - jupyter_contrib_nbextensions
      - jupyterlab
      - jupyterlab-git
      - jupytext
      - libblas=*=*mkl*
      - librosa
      - libxscrnsaver-cos6-x86_64
      - line_profiler
      - metakernel
      - more-itertools
      - mpi4py
      - nbdime
      - nbstripout
      - nbval
      - nitime
      - nltk
      - nose
      - networkx
      - numba
      - numexpr
      - numpy
      - openpyxl
      - opencv
      - pandera
      - pango
      - patchelf
      - path.py
      - pathlib2
      - pbr
      - pep8
      - phonopy
      - pipdeptree
      - pkginfo
      - plotly
      - ply
      - poetry
      - py
      - py-lief
      - pyarrow
      - pybind11
      - pybullet
      - pycrypto
      - pycurl
      - pydantic
      - pympler
      - pyqtwebengine
      - pysoundfile
      - pytest
      - pytest-astropy
      - python-igraph
      - python-libarchive-c
      - python-snappy
      - requests>=2.28
      - ripgrep
      - scalene
      - scikit-image
      - seaborn
      - sh
      - shapely
      - simplegeneric
      - singledispatch
      - sortedcollections
      - sphinx_rtd_theme
      - sphinxcontrib-websupport
      - spyder
      - spyder-line-profiler
      - sympy
      - twisted
      - typing
      - typer
      - unicodecsv
      - unixodbc
      - xarray
      - xgboost
      - xlsxwriter
      - xlwt
      - xmltodict
  triton-r-generic:
    conda_packages:
      - r-essentials
      - rstudio
      - "'blas * mkl'"
  neuroimaging:
    conda_packages:
      - python==3.9
      - cudatoolkit=11.6
      - cupy
      - cython
      - darkdetect
      - datalad
      - dipy
      - doit
      - h5py
      - imageio
      - imageio-ffmpeg>=0.4.1
      - importlib_resources
      - ipympl
      - ipyvtklink
      - ipywidgets
      - joblib
      - jupyter
      - jupyter_client!=6.1.5
      - libblas=*=*mkl*
      - mamba
      - matplotlib
      - mffpy>=0.5.7
      - mne
      - nibabel
      - nilearn
      - numba
      - numexpr
      - numpy
      - pandas
      - pillow
      - pip
      - psutil
      - pyface
      - pyqt!=5.15.3
      - PySurfer
      - python-picard
      - pyvista>=0.30
      - pyvistaqt>=0.4
      - qdarkstyle
      - scikit-learn
      - scipy
      - spyder
      - spyder-kernels>=1.10.0
      - spyder-line-profiler
      - statsmodels
      - torchaudio
      - torchvision
      - tqdm
      - traits
      - traitsui
      - vtk>=9.0.1
      - xlrd
    pip_packages:
      - autoreject
      - bids_validator
      - codespell
      - filename-templates
      - imageio-ffmpeg>=0.4.1
      - json-tricks
      - jupyter_contrib_nbextensions
      - mne-bids
      - mne-rsa
      - mne-nirs
      - mne-connectivity
      - moviepy
      - nipy
      - nipype
      - nitime
      - pyosf
      - pytest-faulthandler
      - pytest-sugar
      - python-bidi
      - python-picard
      - sphinx_bootstrap_theme
      - sphinx_fontawesome
      - sphinx-gallery
      - "https://github.com/AaltoImagingLanguage/conpy/archive/master.zip"
      - "https://github.com/wmvanvliet/posthoc/archive/master.zip"
      - "https://github.com/wmvanvliet/mne_microstates/archive/master.zip"
