[]
#- method: rsync
#  target_host: triton
#  source: /share/apps/spack/envs/fgci-centos7-haswell
#  dest: /share/apps/spack/envs/fgci-centos7-haswell
#  rsync_flags: -surlptDxv --exclude='.nfs*'
#  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
#  delete: false
