config:
  install_tree: /share/apps/spack/envs/fgci-centos7-avx-dev/software
  install_path_scheme: '${PACKAGE}/${VERSION}/${HASH:7}'
  module_roots:
    tcl: /share/apps/spack/envs/fgci-centos7-avx-dev/modules
    lmod: /share/apps/spack/envs/fgci-centos7-avx-dev/lmod
  source_cache: /cache/spack
  misc_cache: /tmp/spack_misc_cache
  build_stage:
    - $spack/var/spack/stage
  locks: false
