- method: rsync
  source: /m/scicomp/software/spack/aalto-ubuntu2204-skylake-dev/software
  dest: /tw-scicomp/software
  rsync_flags: -surlptDxv  --exclude='.nfs*' --exclude='.snapshot*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  use_ssh: False
  delete: false
- method: rsync
  source: /m/scicomp/software/spack/aalto-ubuntu2204-skylake-dev/lmod
  dest: /tw-scicomp/lmod
  rsync_flags: -surlptDxv  --exclude='.nfs*' --exclude='.snapshot*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  use_ssh: False
  delete: false
