installer_checksums:
  Miniconda3-py37_4.9.2-Linux-x86_64.sh: '79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31'
  Miniconda3-py38_4.9.2-Linux-x86_64.sh: '1314b90489f154602fd794accfc90446111514a5a72fe1f71ab83e07de9504a7'
  Miniconda3-py38_4.10.3-Linux-x86_64.sh: '935d72deb16e42739d69644977290395561b7a6db059b316958d97939e9bdf3d'
  Miniconda3-py39_4.10.3-Linux-x86_64.sh: '1ea2f885b4dbc3098662845560bc64271eb17085387a70c2ba3f29fff6f8d52f'
  Mambaforge3-23.1.0-3-Linux-x86_64.sh: 'b7038f4f4d972fa2589dd9edd014940b94600589f924cc6d35a9b11d37506c25'
environments:
  - name: jupyter-generic
    version: '2023-07-10-dev1'
    mambaforge: True
    python_version: 3
    installer_version: '23.1.0-3'
    conda_pack: True
    condarc_install:
      channels:
        - pytorch
        - conda-forge
        - defaults
    condarc_postinstall:
      pkgs_dirs:
        - '~/.conda/pkgs'
      ssl_verify: /etc/ssl/certs/ca-certificates.crt
    collections:
      - compilers
      - mamba
      # - nbconvert_5_pin
      - jupyter-generic
      - scipy-notebook-upstream
      - tensorflow
      - torch
      - pystan
      - scikit_learn
      - opencv
      - bdaaccounting
collections:
  compilers:
    conda_packages:
      - compilers
  mamba:
    conda_packages:
      - mamba
      - conda-tree
  nbconvert_5_pin:
    conda_packages:
      - nbconvert<6
  jupyter-generic:
    conda_packages:
      #- cma          # cma: ??
      - networkx     # networkx: complex networks (general)
      - nose         # nose: mlbp2018, snlp2022 (RT#20396)
      - pandas-datareader
      - plotly       # plotly: student request
      - pydotplus    # pydotplus - dsfb2018 instructor request
      - arviz        # arviz: bayesian data analysis
      - folium       # folium: BE remote sensing course
      - python-igraph  # igraph: complex networks (general)
      - feather-format
      - librosa      # librarosa: datasci2018
      #- bcolz        # bcolz        - introai2019  # now unmaintained, python <3.7
      - tqdm         # tqdm         - introai2019
      - wordcloud    # wordcloud - datasci2019
      - geopy        # geopy - datasci2019
      - rasterio     # rasterio: BE remote sensing course
      #- lapack       # lapack       - dependency for cvxpy
      - nltk         # nltk         -  datasci2019  (use conda  when upgrading)
      - owslib       # owslib: mlpython
      - lifelines
      #- rpy2
      #- shap
      - xlsxwriter
      - xlwt
      - prompt_toolkit
      #- mne
      - pycox
      - pydub        # ???
      - cvxopt       # cvxopt       - mlkern2019
      - cvxpy        # cvxpy        - mlkern2019
      - geoplotlib
      - configargparse # configargparse: deeplearn2020, also generally useful
      - metakernel
      - ortools-python      # ortools:   ai2020
      - xgboost      # dsfbi2022 RT#20284
      - spectrum     # ELEC-C5212: RT#21070
      - jsonpickle   # dlpython2022: RT#22328
      - einops       # deeplearn2023: RT#21983
      - vaderSentiment  # dhhb2022: RT#22440
      - nilearn      # hona2023-brain, RT#22805
      - nibabel      # hona2023-brain, RT#22805
      - statsforecast   # bdaaccounting2023
      - transformers # css2023, RT#23019
    pip_packages:
      - plotchecker  # plotchecker: for nbgrader, mlbp2018
      - gpflow       # special course Gaussian Processes, 2019 RT#14430
                     # 2023-07, c-f has old version (feedstock is unmaintained: https://github.com/conda-forge/gpflow-feedstock)
      - calysto      # 2021-11, c-f missing
      - qiskit       # Introduction to Quantum Technologies, RT#14866
      - liwc         # dhhb2022: RT#22440
      - Wikipedia-API         # css2023, RT#23260
      #- pysurvival (Supported for Python<=3.7 https://github.com/berleon/pysurvival#what-is-pysurvival)
      #- https://github.com/AntoinePassemiers/Lexicon-Based-Sentiment-Analysis/archive/283a2c819016e9a90d408bc82c6edbcd4104be9c.zip
    # Currently non-functional packages:
    #   geopandas (conda-forge)
    #   rasterio (conda-forge)
  scipy-notebook-upstream:
    # Synced from
    # https://github.com/jupyter/docker-stacks/blob/main/scipy-notebook/Dockerfile
    # Re-sync occassionally, copy-and-repasted the whole thing
    # But remove this line: 'conda-forge::blas=*=openblas'
    conda_packages:
      # - 'altair'
      - 'beautifulsoup4'
      - 'bokeh'
      - 'bottleneck'
      - 'cloudpickle'
      - 'cython'
      - 'dask'
      - 'dill'
      - 'h5py'
      - 'ipympl'
      - 'ipywidgets'
      - 'jupyterlab-git'
      - 'matplotlib-base'
      - 'numba'
      - 'numexpr'
      - 'openpyxl'  # Also RT#20808
      - 'pandas'
      # - 'patsy'
      # - 'protobuf'
      - 'pytables'
      - 'scikit-image'
      - 'scikit-learn'  # Also in the scikit_learn collection
      - 'scipy'
      - 'seaborn'
      - 'sqlalchemy'
      - 'statsmodels'
      - 'sympy'
      - 'widgetsnbextension'
      - 'xlrd'
  tensorflow:
    conda_packages:
      - tensorflow-cpu=2.*  # version unpinned for now as a test
      - tensorboard
      - tensorflow-hub
      - keras
  # pystan: general use, bayes course (updated prompt_toolkit needed as dependency)
  pystan:
    conda_packages:
      - pystan
  torch:
    conda_packages:
      - pytorch
      - cpuonly
      - torchtext
      - torchvision=*=*_cpu
  scikit_learn:
    conda_packages:
      - imbalanced-learn
      - scikit-learn # scikit-learn: mlbp2018
      - scikit-plot
      - scikit-survival
      - sklearn-pandas
      - mlxtend      # depends on scikit-learn
      - geopandas    # geopandas: BE remote sensing course
                     # depends on scikit-learn via mapclassify
  opencv:
    conda_packages:
      - opencv       # opencv: mlpython
  bdaaccounting:
    # apt: unixodbc-dev - does this need to be installed on the builder?
    conda_packages:
      - gensim
      - freetds
      - pdfplumber
      - pmdarima
      - pyodbc
      - tweepy
      - unixodbc
