config:
  install_path: /work/modules/automatic/anaconda/envs/aalto-jupyter-anaconda-dev/software
  module_path: /work/modules/automatic/anaconda/envs/aalto-jupyter-anaconda-dev/modules
  source_cache: /cache/anaconda
  tmpdir: /tmp/anaconda
  remove_after_update: True
