config:
  install_path: /m/scicomp/software/anaconda-ci/aalto-jupyter-anaconda-dev/software
  module_path: /m/scicomp/software/anaconda-ci/aalto-jupyter-anaconda-dev/modules
  conda_pack_path: /m/scicomp/software/anaconda-ci/aalto-jupyter-anaconda-dev/packs
  source_cache: /cache/anaconda
  tmpdir: /tmp/anaconda
  remove_after_update: True
