installer_checksums:
  Miniconda3-py37_4.9.2-Linux-x86_64.sh: '79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31'
  Miniconda3-py38_4.9.2-Linux-x86_64.sh: '1314b90489f154602fd794accfc90446111514a5a72fe1f71ab83e07de9504a7'
  Miniconda3-py38_4.10.3-Linux-x86_64.sh: '935d72deb16e42739d69644977290395561b7a6db059b316958d97939e9bdf3d'
  Miniconda3-py39_4.10.3-Linux-x86_64.sh: '1ea2f885b4dbc3098662845560bc64271eb17085387a70c2ba3f29fff6f8d52f'
  Mambaforge-4.11.0-0-Linux-x86_64.sh: '49268ee30d4418be4de852dda3aa4387f8c95b55a76f43fb1af68dcbf8b205c3'
  Mambaforge-22.11.1-4-Linux-x86_64.sh: '16c7d256de783ceeb39970e675efa4a8eb830dcbb83187f1197abfea0bf07d30'
  Miniforge3-4.12.0-2-Linux-x86_64.sh: 'e8bd60572d1bdcd9fc16114f423653c95e02f0be1393383f77fba17cf8acb10e'
  Miniforge3-22.11.1-4-Linux-x86_64.sh: '737d1b2666528416706a916b355c43ff58deeaebf5ca906bc1a551e96c73ab8e'
environments:
  - name: miniconda
    version: '4.9.2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.9.2'
    freeze: True
    condarc_install:
      channels:
        - defaults
  - name: anaconda
    version: '2021-04-tf2'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.10.3'
    freeze: True
    condarc_install:
      channels:
        - pytorch
        - conda-forge
        - gurobi
        - IBMDecisionOptimization
        - mosek
      channel_priority: flexible
    collections:
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - mne
      - gurobi
      - cplex
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: anaconda
    version: '2022-03'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    conda_override_cuda: '11.3'
    freeze: True
    condarc_install:
      channels:
        - pytorch
        - huggingface
        - conda-forge
        - mosek
      channel_priority: flexible
    collections:
      - deep_learning_extras
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - gurobi_pip
      - mne
      - cplex_pip
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: anaconda
    version: '2023-01'
    miniconda: False
    miniforge: False
    mambaforge: True
    mamba: True
    python_version: 3
    installer_version: '22.11.1-4'
    conda_override_cuda: '11.7'
    freeze: True
    condarc_install:
      channels:
        - pytorch
        - nvidia
        - huggingface
        - conda-forge
        - pyg
        - gurobi
        - mosek
      channel_priority: flexible
    collections:
      - deep_learning_extras
      - tensorflow-v2-conda-forge
      - pytorch
      - triton-generic
      - gurobi
      - mne
      - cplex_pip
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
        GRB_LICENSE_FILE: '/m/scicomp/software/manual_installations/software/gurobi/license/gurobi.lic'
  - name: rapidsai
    version: '21.10'
    miniconda: True
    python_version: 3
    installer_version: 'py38_4.10.3'
    freeze: True
    condarc_install:
      channels:
        - rapidsai
        - nvidia
        - conda-forge
        - gurobi
        - IBMDecisionOptimization
        - mosek
      channel_priority: flexible
    collections:
      - rapidsai
      - triton-generic
      - gurobi
      - cplex
      - mosek
    extra_module_variables:
      setenv:
        GUROBI_HOME: '$prefix'
  - name: neuroimaging
    version: '2021-02'
    miniconda: True
    python_version: 3
    installer_version: 'py39_4.10.3'
    freeze: True
    condarc:
      channels:
        - defaults
        - conda-forge
    collections:
      - neuroimaging
  - name: neuroimaging
    version: '2023-02'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '4.12.0-2'
    freeze: True
    conda_override_cuda: '11.7'
    condarc_install:
      channels:
        - pytorch
        - nvidia
        - huggingface
        - conda-forge
        - pyg
      channel_priority: flexible
    collections:
      - triton-generic
      - deep_learning_extras
      - pytorch
      - neuroimaging
  - name: neuroimaging
    version: '2023-03'
    miniconda: False
    miniforge: True
    mamba: True
    python_version: 3
    installer_version: '22.11.1-4'
    conda_override_cuda: '11.7'
    condarc_install:
      channels:
        - pytorch
        - nvidia
        - huggingface
        - conda-forge
        - pyg
      channel_priority: flexible
    collections:
      - triton-generic
      - deep_learning_extras
      - pytorch
      - neuroimaging
collections:
  cplex:
    conda_packages:
      - cplex
  cplex_pip:
    pip_packages:
      - cplex
  gurobi:
    conda_packages:
      - gurobi=9.5.2
  gurobi_pip:
    pip_packages:
      - gurobipy
  mosek:
    conda_packages:
      - mosek
  tensorflow-v1:
    conda_packages:
      - tensorboard
      - tensorboard-plugin-wit
      - tensorflow=1.15.0
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  tensorflow-v2:
    conda_packages:
      - cudatoolkit
      - tensorboard
      - tensorboard-plugin-wit
      - tensorflow=2.4.1=gpu_*
      - tensorflow-base
      - tensorflow-estimator
      - tensorflow-gpu
  tensorflow-v2-pip:
    # Check this page for compatible versions of tensorflow, cudatoolkit and cudnn.
    # https://www.tensorflow.org/install/source#gpu
    conda_packages:
      - absl-py
      - astunparse
      - cudatoolkit=11.2.*
      - cudatoolkit-dev=11.2.*
      - cudnn=8.1.*
      - gast
      - google-pasta
      - grpcio
      - h5py
      - keras-preprocessing
      - libgcc-ng
      - libstdcxx-ng
      - numpy
      - opt_einsum
      - protobuf
      - python-flatbuffers
      - scipy
      - six
      - sqlite
      - termcolor
      - wrapt
      - zlib
    pip_packages:
      - tensorflow==2.6.0
  tensorflow-v2-conda-forge:
    conda_packages:
      - cudatoolkit=11.*
      - cudnn>=8.2
      - tensorboard
      - tensorflow=2.10=cuda11*
  rapidsai:
    conda_packages:
      - cudatoolkit=11.4
      - cudf
      - cuml
      - cugraph
      - cusignal
      - cuspatial
      - cuxfilter
      - rapids-blazing=21.10
  pytorch:
    conda_packages:
      - cudnn>=8.3
      - pytorch::pytorch
      - pytorch::pytorch-cuda=11.7
      - pytorch::torchaudio
      - pytorch::torchvision
      - pytorch::pytorch-mutex=*=cuda
  deep_learning_extras:
    conda_packages:
      - cudatoolkit>=11.3
      - cudnn>=8.3
      - datasets
      - dm-haiku
      - dm-sonnet
      - flax
      - gymnasium
      - jax
      - ogb
      - pyg
      - pytorch-lightning
      - py-xgboost
      - transformers
      - tensorboardx
      - wandb
    pip_packages:
      - deepspeed
      - reverb
      # Ray's conda package depends on nvidia-ml-py, which conflicts with scalene
      - ray[default]
      - ray[air]
      - ray[data]
      - ray[tune]
      - ray[rllib]
  mne:
    conda_packages:
      - mne
  triton-generic:
    pip_packages:
      - bash-kernel
      - forthon
      - matlab-kernel
      - mppl
      - nbscript
      - nbzip
      - pymanopt
      - snakemake
    conda_packages:
      - astropy
      - attrs
      # - bcolz # No longer maintained
      - beautifulsoup4
      - bitarray
      # - blaze # No python3.8 build
      - black
      - boto
      - bottleneck
      - cartopy
      #- clyent # Deprecated package
      - conda-tree
      - configargparse
      - contextlib2
      - crc32c
      - cython
      - dask
      - datalad
      - dill
      - docopt
      - easygui
      - fastapi
      - filelock
      - flake8
      - glob2
      - gpy
      - graph-tool
      - greenlet
      - h5py=*=mpi_openmpi*
      - h5netcdf
      - hdf5=*=mpi_openmpi*
      - html5lib
      - hydra-core
      - igraph
      - importnb
      - iniconfig
      - ipdb
      - ipympl    # jupyter + matplotlib interactive
      - jbig
      - joblib
      - jsonlines
      - jupyter
      - jupyter_contrib_nbextensions
      - jupyterlab
      - jupyterlab-git
      - jupytext
      - libblas=*=*mkl*
      - librosa
      - libxscrnsaver-cos6-x86_64
      - line_profiler
      - metakernel
      - more-itertools
      - mpi4py
      - nbdime
      - nbstripout
      - nbval
      - nitime
      - nltk
      - nose
      - networkx
      - numba
      - numexpr
      - numpy
      - openpyxl
      - opencv
      - pandera
      - pango
      - patchelf
      - path.py
      - pathlib2
      - pbr
      - pep8
      - phonopy
      - pipdeptree
      - pkginfo
      - plotly
      - ply
      - poetry
      - prometheus_client<0.14 # Limit prometheus-client version for ray
      - py
      - py-lief
      - pyarrow>=7,<8=*cuda
      - pybind11
      - pybullet
      #- pycrypto # No longer maintained
      - pycurl
      - pydantic
      - pympler
      - pyqtwebengine
      - pysoundfile
      - pytest
      - pytest-astropy
      - python-igraph
      - python-libarchive-c
      - python-snappy
      - requests>=2.28
      - ripgrep
      - scalene
      - scikit-image
      - seaborn
      - sh
      - shapely
      - simplegeneric
      - singledispatch
      - sortedcollections
      - sphinx_rtd_theme
      - sphinxcontrib-websupport
      - spyder>=5.4.2 # Fixes OOD bug
      - spyder-line-profiler
      - sympy
      - twisted
      - typing
      - typer
      - ucx
      - unicodecsv
      - unixodbc
      - webdataset
      - xarray
      - xgboost
      - xlsxwriter
      - xlwt
      - xmltodict
  neuroimaging:
    conda_packages:
      - autoreject
      - bids-validator
      - cupy
      - fooof
      - gensim
      - mne
      - mne-bids
      - mne-connectivity
      - mne-faster
      - mne-microstates
      - mne-nirs
      - mne-qt-browser
      - mne-rsa
      - neurokit2
      - nipype
      - nitime
      - numba
      - psychopy
      - pydata-sphinx-theme
      - pydocstyle
      - pyosf
      - pytest-faulthandler
      - pytest-sugar
      - python-bidi
      - python-picard
      - pyvista>=0.30
      - pyvistaqt>=0.4
      - qdarkstyle
      - scikit-learn
      - sphinx-gallery
      - statsmodels
    pip_packages:
      - "https://github.com/wmvanvliet/posthoc/archive/master.zip"
      - "https://github.com/AaltoImagingLanguage/conpy/archive/master.zip"
      - filename-templates
      - psychtoolbox
      - pygame
      - pyo
      - pyparallel
      - rapidtide
      - sphinx-bootstrap-theme
      - sphinxcontrib-bibtex
      - sphinxcontrib-youtube
      - sphinx-copybutton
      - sphinx-design
      - sphinx-fontawesome
      - websocket_client
