config:
  install_path: /m/scicomp/software/anaconda-ci/aalto-ubuntu2004-anaconda-dev/software
  module_path: /m/scicomp/software/anaconda-ci/aalto-ubuntu2004-anaconda-dev/modules
  source_cache: /cache/anaconda
  tmpdir: /tmp/anaconda
  remove_after_update: True
