- method: rsync
  source: /m/scicomp/software/anaconda-ci/aalto-ubuntu2004-anaconda-dev/software
  dest: /tw-scicomp/software
  rsync_flags: -surlptDxv  --exclude='.nfs*' --exclude='.snapshot*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  use_ssh: False
  delete: True
- method: rsync
  source: /m/scicomp/software/anaconda-ci/aalto-ubuntu2004-anaconda-dev/modules
  dest: /tw-scicomp/modules
  rsync_flags: -surlptDxv  --exclude='.nfs*' --exclude='.snapshot*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  use_ssh: False
  delete: True
