config:
  install_path: /m/work/modules/automatic/singularity/envs/aalto-ubuntu1804-dev/software
  module_path: /m/work/modules/automatic/singularity/envs/aalto-ubuntu1804-dev/modules
  source_cache: /cache/singularity/source
  tmpdir: /tmp/singularity
  build_stage: /cache/singularity/stage
  wrapper_path: /m/work/modules/automatic/singularity/singularity-wrapper/bin
  remove_after_update: True
  sudo: False
  fakeroot: True
  debug: False
