target_architecture:
  platform: linux
  os: centos7
  arch: haswell
build_options:
  reuse_packages: false
compilers:
  - name: 'gcc'
    version: 4.8.5
    system_compiler: true
    flags:
      cflags: -O2 -g
      cxxflags: -O2 -g
      fflags: -O2 -g
  - name: 'gcc'
    version: 9.3.0
    variants:
      - '+piclibs'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=haswell -ftree-vectorize
      cxxflags: -O2 -g -march=haswell -ftree-vectorize
      fflags: -O2 -g -march=haswell -ftree-vectorize
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'gcc'
    version: 6.5.0
    variants:
      - '+piclibs'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=haswell -ftree-vectorize
      cxxflags: -O2 -g -march=haswell -ftree-vectorize
      fflags: -O2 -g -march=haswell -ftree-vectorize
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'gcc'
    version: 8.4.0
    variants:
      - '+piclibs'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=haswell -ftree-vectorize
      cxxflags: -O2 -g -march=haswell -ftree-vectorize
      fflags: -O2 -g -march=haswell -ftree-vectorize
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'gcc'
    version: 11.2.0
    variants:
      - '+piclibs'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=haswell -ftree-vectorize
      cxxflags: -O2 -g -march=haswell -ftree-vectorize
      fflags: -O2 -g -march=haswell -ftree-vectorize
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'intel-parallel-studio'
    version: 'cluster.2020.0'
    licenses:
      - 'license.lic'
    variants:
      - '+mpi'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=haswell
      cxxflags: -O2 -g -march=haswell
      fflags: -O2 -g -march=haswell
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'intel-oneapi-compilers'
    version: '2021.2.0'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=haswell
      cxxflags: -O2 -g -march=haswell
      fflags: -O2 -g -march=haswell
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'intel-oneapi-compilers'
    version: '2021.3.0'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=haswell
      cxxflags: -O2 -g -march=haswell
      fflags: -O2 -g -march=haswell
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
packages:
  - name: 'abinit'
    version: '8.10.3'
    variants:
      - '+mpi'
      - '+openmp'
      - '+scalapack'
  - name: 'cuda'
    version: '10.1.243'
  - name: 'cuda'
    version: '11.0.2'
  - name: 'cuda'
    version: '11.2.1'
  - name: 'julia'
    version: '1.5.3'
    extra_flags:
      - '-j 1'
  - name: 'llvm'
    version: 11.0.1
    variants:
      - '~omp_as_runtime'
    extra_flags:
      - '-j 4'
  - name: 'llvm'
    version: 11.0.1
    variants:
      - '~omp_as_runtime'
      - '+cuda'
      - 'cuda_arch=35,60,70'
    dependencies:
      - '^cuda@10.1.243'
    extra_flags:
      - '-j 4'
#  - name: 'quantum-espresso'
#    version: '6.6'
#    variants:
#      - '+epw'
#      - 'hdf5=parallel'
#      - '+mpi'
#      - '+scalapack'
  - name: 'hdf5'
    version: 1.10.7
    variants:
      - '~mpi'
  - name: 'relion'
    version: '3.1.3'
    variants:
      - '+cuda'
      - 'cuda_arch=35,60,70,80'
      - '+gui'
  - name: 'hpl'
    version: '2.3'
  - name: 'gromacs'
    version: '2020.4'
    variants:
      - '+blas'
      - '+mpi'
      - '+openmp'
  - name: 'mdsplus'
    version: 'stable_release-7-96-17'
    dependencies:
      - '^openjdk@11.0.8_10'
  - name: 'mesa'
    version: '21.0.3'
    extra_flags:
      - '-j 1'
  - name: 'mesa'
    version: '21.2.3'
    extra_flags:
      - '-j 1'
  - name: 'geant4'
    version: '10.7.1'
    variants:
      - '+ipo'
      - '+python'
  - name: 'gsl'
    version: '2.6'
  - name: 'libsvm'
    version: '323'
  - name: 'libxscrnsaver'
    version: '1.2.2'
  - name: 'xterm'
    version: '353'
  - name: 'snakemake'
    version: '6.1.1'
  - name: 'emacs'
    version: '27.1'
  - name: 'bazel'
    version: '3.7.1'
    dependencies:
      - '^openjdk@11.0.8_10'
  - name: 'mpifileutils'
    version: '0.11'
    variants:
      - '+xattr'
  - name: 'ants'
    version: '2.3.5'
    variants:
      - '~tests'
  - name: 'namd'
    version: '2.14'
    dependencies:
      - '^charmpp@6.10.2'
  - name: 'ior'
    version: '3.3.0'
  - name: 'julia'
    version: '1.6.0'
    extra_flags:
      - '-j 1'
  - name: 'julia'
    version: '1.6.1'
    extra_flags:
      - '-j 1'
  - name: 'julia'
    version: '1.6.2'
    extra_flags:
      - '-j 1'
  - name: 'nvhpc'
    version: '21.5'
  - name: 'openblas'
    version: '0.3.14'
  - name: 'openblas'
    version: '0.3.17'
  - name: 'stress'
    version: '1.0.4'
  - name: 'openbabel'
    version: '3.1.1'
    extra_flags:
      - '-j 1'
  - name: 'rclone'
    version: '1.56.0'
  - name: 'py-virtualenv'
    version: '16.7.6'
  - name: 'flac'
    version: '1.3.3'
#  - name: 'rstudio'
#    version: '1.4.1717'
  - name: 'cuda-memtest'
    version: 'master'
  - name: 'gsl'
    version: '2.7'
  - name: 'openfoam-org'
    version: '9'
    variants:
      - '+source'
      - '+metis'
  - name: 'suite-sparse'
    version: '5.10.1'
    variants:
      - '+openmp'
      - '+pic'
  - name: 'quantum-espresso'
    version: '6.8'
    variants:
      - '+epw'
      - 'hdf5=parallel'
      - '+mpi'
      - '+scalapack'
    extra_flags:
      - '-j 1'
  - name: 'netcdf-cxx4'
    version: '4.3.1'
  - name: 'fmt'
    version: '8.0.1'
  - name: 'jq'
    version: '1.6'
  - name: 'p7zip'
    version: '16.02'
  - name: 'cp2k'
    version: '8.2'
    variants:
      - '~cuda'
      - '+mpi'
      - '+openmp'
  - name: 'cp2k'
    version: '8.2'
    variants:
      - '+cuda'
      - '+mpi'
      - '+openmp'
      - '+cuda_blas'
      - '+cuda_fft'
      - 'cuda_arch=60'
  - name: 'cp2k'
    version: '8.2'
    variants:
      - '+cuda'
      - '+mpi'
      - '+openmp'
      - '+cuda_blas'
      - '+cuda_fft'
      - 'cuda_arch=70'
  - name: 'libgd'
    version: '2.2.4'
  - name: 'freesurfer'
    version: '7.2.0'
    licenses:
      - 'license.txt'
  - name: 'mumax'
    version: '3.10'
    variants:
      - '+cuda'
      - 'cuda_arch=60,70,80'
  - name: 'intel-oneapi-mkl'
    version: '2021.3.0'
    dependencies:
      - '^intel-oneapi-tbb@2021.3.0'
  - name: 'mujoco'
    version: '2.1.0'
  - name: 'mujoco'
    version: '2.1.1'
    variants:
      - 'osmesa=8'
