- method: rsync
  target_host: triton
  source: /share/apps/spack/envs/fgci-centos7-haswell-dev/software
  dest: /share/apps/spack/envs/fgci-centos7-haswell-dev/software
  rsync_flags: -surlptDxv  --exclude='.nfs*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  delete: true
- method: rsync
  target_host: triton
  source: /share/apps/spack/envs/fgci-centos7-haswell-dev/lmod
  dest: /share/apps/spack/envs/fgci-centos7-haswell-dev/lmod
  rsync_flags: -surlptDxv  --exclude='.nfs*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  delete: true
- method: rsync
  target_host: scibuilder
  source: /share/apps/spack/envs/fgci-centos7-haswell-dev/software
  dest: /tw-scicomp/spack/envs/fgci-centos7-haswell-dev/software
  rsync_flags: -surlptDxv  --exclude='.nfs*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  delete: true
- method: rsync
  target_host: scibuilder
  source: /share/apps/spack/envs/fgci-centos7-haswell-dev/lmod
  dest: /tw-scicomp/spack/envs/fgci-centos7-haswell-dev/lmod
  rsync_flags: -surlptDxv  --exclude='.nfs*'
  chmod_options: 'Dg+s,ug+w,Fo-w,+X'
  delete: true
