packages:
  cairo:
    variants: +X +gobject +pdf
  curl:
    variants: +libssh2 ~nghttp
  fontconfig:
    version: [2.13.1]
  gcc:
    version: [9.3.0]
    variants: +piclibs
  go:
    version: [1.15.6]
  graphviz:
    variants: +expat +ghostscript +gtkplus +gts +java +libgd +pangocairo +qt
  hdf5:
    variants: +cxx +fortran +hl +pic +shared +szip +threadsafe
  latte:
    variants: +progress
  llvm:
    variants: +python
  m4:
    externals:
      - spec: m4@1.4.16
        prefix: /usr
    buildable: False
  mesa:
    variants: +glx +llvm +opengl +osmesa swr=none
  netcdf-c:
    version: [4.7.4]
  openblas:
    version: [0.3.13]
    variants: +virtual_machine threads=openmp +pic
  openmpi:
    version: [4.0.5]
    variants: fabrics=verbs +pmi +thread_multiple schedulers=slurm +legacylaunchers
  openssl:
    externals:
      - spec: openssl@1.0.2k
        prefix: /usr
    buildable: False
  pango:
    variants: +X
  pcre:
    variants: +jit +utf
  python:
    version: [3.8.7]
    variants: +pic +shared +optimizations +uuid +pythoncmd
  qmd-progress:
    variants: +graphlib
  qt:
    variants: +phonon +dbus +opengl +webkit
  r:
    version: [4.0.3]
    variants: +X +external-lapack
  slurm:
    externals:
      - spec: slurm@18-08-8-1
        prefix: /usr
    buildable: False
  sqlite:
    version: [3.34.0]
    variants: +column_metadata +fts +functions +rtree
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      gl: [mesa]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
