command_collections:
  common:
    post_commands:
      - 'mkdir /u'
      - 'for i in $(seq 0 9); do for j in $(seq 0 9) ; do ln -s /m/home/home$i/$i$j /u/$i$j ; done ; done'
      - 'mkdir /scratch'
      - 'mkdir /m'
      - 'mkdir /l'
      - 'mkdir /raid'
      - 'mkdir /share'
      - 'mkdir -p /opt/mellanox'
      - 'mkdir -p /var/singularity/mnt/final/usr/bin'
  compilers:
    post_commands:
      - 'apt-get update'
      - 'apt-get -y install -q build-essential g++'
      - 'rm -rf /var/lib/apt/lists/*'
flag_collections:
  common:
    - '-B /m:/m'
    - '-B /l:/l'
    - '-B /scratch:/scratch'
  cntk:
    - '-B /tmp:/run/lock'
  nvidia:
    - '--nv'
  openpose:
    - '--pwd /opt/openpose'
definitions:
  - name: 'nvidia-cntk'
    docker_user: 'nvidia'
    docker_image: 'cntk'
    registry: 'nvcr.io'
    module_namespace: 'common'
    tags:
      - '18.08-py3'
    command_collections:
      - 'common'
    flag_collections:
      - 'common'
      - 'nvidia'
      - 'cntk'
  - name: 'nvidia-pytorch'
    docker_user: 'nvidia'
    docker_image: 'pytorch'
    registry: 'nvcr.io'
    module_namespace: 'common'
    tags:
      - '20.02-py3'
    command_collections:
      - 'common'
      - 'compilers'
    flag_collections:
      - 'common'
      - 'nvidia'
  - name: 'nvidia-tensorflow'
    docker_user: 'nvidia'
    docker_image: 'tensorflow'
    registry: 'nvcr.io'
    module_namespace: 'common'
    tags:
      - '20.02-tf1-py3'
      - '20.02-tf2-py3'
    command_collections:
      - 'common'
      - 'compilers'
    flag_collections:
      - 'common'
      - 'nvidia'
  - name: 'singularity-openpose'
    docker_user: 'aaltoscienceit'
    docker_image: 'openpose'
    registry: 'registry.cs.aalto.fi'
    module_namespace: 'common'
    tags:
      - 'v1.5.1'
    command_collections:
      - 'common'
    flag_collections:
      - 'common'
      - 'nvidia'
      - 'openpose'
