config:
  install_path: /share/apps/anaconda-ci/fgci-centos7-anaconda/software
  module_path: /share/apps/anaconda-ci/fgci-centos7-anaconda/modules
  source_cache: /cache/anaconda
  tmpdir: /tmp/anaconda
  remove_after_update: True
