config:
  install_tree:
    projections:
      all: ${PACKAGE}/${VERSION}/${HASH:7}
    root: /m/scicomp/software/spack/aalto-ubuntu2004-skylake/software
  module_roots:
    tcl: /m/scicomp/software/spack/aalto-ubuntu2004-skylake/modules
    lmod: /m/scicomp/software/spack/aalto-ubuntu2004-skylake/lmod
  source_cache: /cache/spack
  misc_cache: /tmp/spack_misc_cache
  build_stage:
    - $spack/var/spack/stage
  locks: false
  build_language: 'en_US.utf8'
